//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Almacen.Web.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Producto
	{
		public int ID
		{
			get;
			set;
		}

		public int IDCategoria
		{
			get;
			set;
		}

		public string Nombre
		{
			get;
			set;
		}

		public virtual decimal Precio
		{
			get;
			set;
		}

		public decimal Existencia
		{
			get;
			set;
		}

		public DateTime UltimoMovimiento
		{
			get;
			set;
		}

		public virtual Categoria Categoria
		{
			get;
			set;
		}

	}
}

